site_name: Cours de Licence 3 ST
docs_dir: Docs/

theme:
  name: material
  palette:
    primary: 'grey'
    accent: 'deep purple'
  feature:
    tabs: true
  language: "fr"
  extra:
    social:
      - type: "github"
        link: "https://github.com/Lizeem"
      - type: "linkedin"
        link: "https://www.linkedin.com/in/emma-lizeski-837899149/"

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.arithmatex